# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoApp

	#Project Utilities
	pod 'SwiftLint'
        pod 'R.swift'
        pod 'Wormholy', :configurations => ['Debug']

	# Requirements
	pod 'PureLayout'
	pod 'Alamofire'
	
	# Dependency Injection
        pod 'Swinject'
        pod 'SwinjectAutoregistration'

	# Image loading
	pod 'Nuke'
 	
	# Reachability
	# pod "Connectivity"



  target 'DemoAppTests' do
    inherit! :search_paths
    # Pods for testing

    # pod 'SnapshotTesting'
    # pod 'SwiftyMocky'
    # pod 'Nimble'
	
  end

end
